//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallLogging_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedMessage
    {
        public int DelMes_UID { get; set; }
        public string DelMes_DESCRIPTION { get; set; }
        public string DelMes_RESPONSE { get; set; }
        public string DelMes_NOTES { get; set; }
        public Nullable<int> DelMes_CompanyId { get; set; }
        public Nullable<int> DelMes_MESSNO { get; set; }
        public string DelMes_DeletedBY { get; set; }
        public Nullable<System.DateTime> DelMes_DateDeleted { get; set; }
        public Nullable<int> DelMes_SYSTIMEREFERENCE { get; set; }
        public string DelMes_FORWARDED { get; set; }
        public string DelMes_URGENT { get; set; }
        public Nullable<byte> DelMes_OPENED { get; set; }
        public Nullable<System.DateTime> DELMES_MessDateTime { get; set; }
        public string DelMes_CUSTCODE { get; set; }
        public Nullable<int> DELMES_CustomerUID { get; set; }
        public string DelMes_CONTACT { get; set; }
        public string DelMes_PHONE { get; set; }
        public string DelMes_TAKENBY { get; set; }
        public string DelMes_STAFFCODE { get; set; }
        public string DelMes_ORDERNO { get; set; }
        public string DelMes_CATEGORY { get; set; }
        public string DelMes_PROBLEM { get; set; }
        public Nullable<short> DelMes_PRIORITY { get; set; }
        public string DelMes_ERROR { get; set; }
        public string DelMes_CHANNEL { get; set; }
        public string DelMes_RECORDNO { get; set; }
        public string DelMes_FILE { get; set; }
        public Nullable<int> DelMes_LINE { get; set; }
        public string DelMes_INPROGRAM { get; set; }
        public string DelMes_FUNCCODE { get; set; }
        public string DelMes_STATUS { get; set; }
        public string DelMes_FORWARDEDTO { get; set; }
        public string DelMes_RESOLVEDON { get; set; }
        public string DelMes_RESOLVEDAT { get; set; }
        public Nullable<System.DateTime> DelMes_FOLLOWUPDATE { get; set; }
        public Nullable<byte> DelMes_PRINTED { get; set; }
    }
}
