//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallLogging_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int DEP_UID { get; set; }
        public Nullable<int> DEP_CompanyId { get; set; }
        public Nullable<int> DEP_DEPID { get; set; }
        public string DEP_DepDesc { get; set; }
        public Nullable<byte> DEP_Secondary { get; set; }
    }
}
