//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallLogging_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MES_UID { get; set; }
        public Nullable<int> MES_CompanyId { get; set; }
        public Nullable<int> MES_MessNo { get; set; }
        public Nullable<int> MES_SystimeReference { get; set; }
        public string MES_Forwarded { get; set; }
        public string MES_Urgent { get; set; }
        public Nullable<byte> MES_Opened { get; set; }
        public Nullable<System.DateTime> MES_MesDateTime { get; set; }
        public string MES_CustCode { get; set; }
        public Nullable<int> MES_CustomerUID { get; set; }
        public string MES_Contact { get; set; }
        public string MES_Phone { get; set; }
        public string MES_TakenBy { get; set; }
        public string MES_StaffCode { get; set; }
        public string MES_StaffDep { get; set; }
        public string MES_OrderNo { get; set; }
        public string MES_Category { get; set; }
        public string MES_Problem { get; set; }
        public Nullable<short> MES_Priority { get; set; }
        public string MES_Error { get; set; }
        public string MES_Channel { get; set; }
        public string MES_RecordNo { get; set; }
        public string MES_File { get; set; }
        public Nullable<int> MES_Line { get; set; }
        public string MES_InProgram { get; set; }
        public string MES_FuncCode { get; set; }
        public string MES_Status { get; set; }
        public Nullable<byte> MES_ProgramReq { get; set; }
        public Nullable<byte> MES_IssueReg { get; set; }
        public Nullable<byte> MES_SamInv { get; set; }
        public string MES_WaitStatus { get; set; }
        public string MES_ForwardedTo { get; set; }
        public Nullable<System.DateTime> MES_ResolvedDateTime { get; set; }
        public Nullable<System.DateTime> MES_FollowUpDate { get; set; }
        public Nullable<byte> MES_Printed { get; set; }
        public Nullable<byte> MES_AcceptTrain { get; set; }
        public string MES_InUseBy { get; set; }
        public string MES_Department { get; set; }
        public string MES_Description { get; set; }
        public string MES_Response { get; set; }
        public string MES_Notes { get; set; }
    }
}
