//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallLogging_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problem
    {
        public int PRO_UID { get; set; }
        public Nullable<int> PRO_CompanyId { get; set; }
        public Nullable<int> PRO_probNo { get; set; }
        public string PRO_category { get; set; }
        public string PRO_Problem { get; set; }
        public Nullable<int> PRO_DepID { get; set; }
    }
}
